name: SOPRA-HRIS FE

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          node-version: "16"
      - run: npm ci
      - run: npm run build
